#!/usr/bin/env python3
"""
ENHANCED TRADING SCRIPT - live_ALANKIT.BO
===================================
Strategy: VWAP with Multi-Filter Confirmation

FILTERS APPLIED:
- Volume: Only trade when volume > 20-day MA
- Trend: Only trade in direction of 50-day MA  
- Volatility: Avoid extremely low/high volatility environments
- RSI: Momentum confirmation

This is an AUTO-GENERATED enhanced version.
Generated by strategy_enhancer.py
"""

#!/usr/bin/env python3
"""
Live Trading Script - ALANKIT.BO
Strategy: VWAP (Volume Weighted Average Price)
Win Rate: 63.64%
Position: ₹7000 | Stop Loss: 0.8% | Target: 4.0x | Daily Loss Cap: 0.3%
"""

import os
import sys
import json
import time
import logging
import groww_api
import requests
from datetime import datetime, time as dtime
from pathlib import Path

try:
    import yfinance as yf
    YFINANCE_AVAILABLE = True
except ImportError:
    YFINANCE_AVAILABLE = False
# ── Logging ───────────────────────────────────────────────────────────────────
LOG_DIR = Path(__file__).parent / "logs"
LOG_DIR.mkdir(exist_ok=True)
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    handlers=[
        logging.FileHandler(LOG_DIR / "live_ALANKIT.BO.log"),
        logging.StreamHandler(sys.stdout),
    ],
)
log = logging.getLogger("live_ALANKIT.BO")

# ── Config ────────────────────────────────────────────────────────────────────
SYMBOL         = "ALANKIT.BO"
STRATEGY       = "VWAP"
POSITION       = 7000

# 3-TIER EXIT SYSTEM
TARGET_1_MULT = 1.5
TARGET_2_MULT = 3.0
TARGET_3_MULT = 5.0
STOP_LOSS_PCT  = 0.006
TARGET_MULT    = 2.5
SIGNAL_MODE   = "MEAN_REVERSION"  # ENHANCED: was BREAKOUT, inverting for low win-rate stock
DAILY_LOSS_CAP = 0.003
PARAMS         = {"vwap_period": 14, "atr_multiplier": 1.0}

GROWW_API_KEY    = os.getenv("GROWW_API_KEY")
GROWW_API_SECRET = os.getenv("GROWW_API_SECRET")
GROWW_API_BASE   = "https://api.groww.in/v1"

IST_TZ_OFFSET = 5.5

# ── Helpers ────────────────────────────────────────────────────────────────────

def ist_now() -> datetime:
    return datetime.utcnow() + __import__("datetime").timedelta(hours=IST_TZ_OFFSET)

# Smart entry: 9:30-14:30 IST
def is_market_open() -> bool:
    now = ist_now()
    if now.weekday() >= 5:
        return False
    return dtime(9, 15) <= now.time() <= dtime(15, 30)

def is_pre_market() -> bool:
    now = ist_now()
    if now.weekday() >= 5:
        return False
    return dtime(9, 0) <= now.time() < dtime(9, 15)

def fetch_recent_data(days: int = 60, retries: int = 3) -> list | None:
    for attempt in range(retries):
        try:
            ticker = yf.Ticker(SYMBOL)
            df = ticker.history(period=f"{days}d")
            if df.empty:
                raise ValueError("Empty dataframe")
            ohlcv = [
                {
                    "date":   str(idx.date()),
                    "open":   float(row["Open"]),
                    "high":   float(row["High"]),
                    "low":    float(row["Low"]),
                    "close":  float(row["Close"]),
                    "volume": int(row["Volume"]),
                }
                for idx, row in df.iterrows()
            ]
            log.info("Fetched %d candles for %s", len(ohlcv), SYMBOL)
            return ohlcv
        except Exception as e:
            log.warning("Attempt %d/%d failed fetching data: %s", attempt + 1, retries, e)
            time.sleep(2 ** attempt)
    log.error("All fetch attempts failed for %s", SYMBOL)
    return None

def calculate_atr(ohlcv: list, period: int = 14) -> list:
    atr = []
    prev_close = None
    for i, bar in enumerate(ohlcv):
        tr = bar["high"] - bar["low"] if prev_close is None else max(
            bar["high"] - bar["low"],
            abs(bar["high"] - prev_close),
            abs(bar["low"]  - prev_close),
        )
        if i < period - 1:
            atr.append(None)
        elif i == period - 1:
            atr.append(tr)
        else:
            atr.append((atr[-1] * (period - 1) + tr) / period)
        prev_close = bar["close"]
    return atr

def calculate_vwap(ohlcv: list, period: int = 14) -> list:
    vwap = []
    for i in range(len(ohlcv)):
        if i < period - 1:
            vwap.append(None)
        else:
            tp_sum  = sum((ohlcv[j]["high"] + ohlcv[j]["low"] + ohlcv[j]["close"]) / 3
                          for j in range(i - period + 1, i + 1))
            vol_sum = sum(ohlcv[j]["volume"] for j in range(i - period + 1, i + 1))
            vwap.append(tp_sum / vol_sum if vol_sum > 0 else 0.0)
    return vwap

def vwap_signal(ohlcv: list, params: dict) -> tuple[str, float, float]:
    period        = params["vwap_period"]
    atr_mult      = params["atr_multiplier"]
    vwap_vals     = calculate_vwap(ohlcv, period)
    atr_vals      = calculate_atr(ohlcv, period)
    signals       = ["HOLD"] * len(ohlcv)

    for i in range(period, len(ohlcv)):
        if vwap_vals[i] is None or atr_vals[i] is None:
            continue
        price    = ohlcv[i]["close"]
        v        = vwap_vals[i]
        a        = atr_vals[i]
        signal_mode = globals().get("SIGNAL_MODE", "BREAKOUT")
        if signal_mode == "MEAN_REVERSION":
            if price < v - a * atr_mult:
                signals[i] = "BUY"
            elif price > v + a * atr_mult:
                signals[i] = "SELL"
        else:
            if price > v + a * atr_mult:
                signals[i] = "BUY"
            elif price < v - a * atr_mult:
                signals[i] = "SELL"

    current_signal = signals[-1] if signals else "HOLD"
    current_price  = ohlcv[-1]["close"]
    current_atr    = atr_vals[-1] if atr_vals and atr_vals[-1] is not None else 0.0
    return current_signal, current_price, current_atr

def place_groww_order(symbol, signal, quantity, price):
    """
    Place order via Groww API or paper trade.
    Uses Bracket Orders (BO) when GROWW_API_KEY is set.
    Falls back to paper trading otherwise.
    """
    import groww_api
    
    if not groww_api.is_configured():
        return groww_api.paper_trade(signal, symbol, price, quantity)
    
    exchange = "NSE"
    
    if signal == "BUY":
        # Calculate target and stop loss  # 0.8% ATR approximation
        stop_loss = price - (atr * 1.0)  # 1x ATR stop
        target = price + (atr * 4.0)  # 4x ATR target
        # Use bracket order for BUY with target + stop loss
        result = groww_api.place_bo(
            exchange=exchange,
            symbol=symbol,
            transaction="BUY",
            quantity=quantity,
            target_price=target,
            stop_loss_price=stop_loss,
            trailing_sl=0.3,
            trailing_target=0.5
        )
    elif signal == "SELL":
        stop_loss = price + (atr * 1.0)
        target = price - (atr * 4.0)
        result = groww_api.place_bo(
            exchange=exchange,
            symbol=symbol,
            transaction="SELL",
            quantity=quantity,
            target_price=target,
            stop_loss_price=stop_loss,
            trailing_sl=0.3,
            trailing_target=0.5
        )
    else:
        return None
    
    if result:
        print("Order placed: {} {} {} @ Rs{:.2f}".format(
            signal, quantity, symbol, price))
    return result


# ============================================================================
# ENHANCED SIGNAL GENERATION - WITH MULTI-FILTER CONFIRMATION
# ============================================================================
# Active filters: volume, trend, volatility, rsi

def calculate_volume_ma(ohlcv: List[dict], period: int = 20) -> float:
    """Calculate 20-day volume moving average."""
    if len(ohlcv) < period:
        return 0
    volumes = [bar["volume"] for bar in ohlcv[-period:]]
    return sum(volumes) / period


def calculate_price_ma(ohlcv: List[dict], period: int = 50) -> float:
    """Calculate N-day moving average of close prices."""
    if len(ohlcv) < period:
        return 0
    closes = [bar["close"] for bar in ohlcv[-period:]]
    return sum(closes) / period


def calculate_atr(ohlcv: List[dict], period: int = 14) -> float:
    """Calculate Average True Range."""
    if len(ohlcv) < period + 1:
        return 0
    tr_values = []
    for i in range(1, len(ohlcv)):
        high = ohlcv[i]["high"]
        low = ohlcv[i]["low"]
        prev_close = ohlcv[i-1]["close"]
        tr = max(high - low, abs(high - prev_close), abs(low - prev_close))
        tr_values.append(tr)
    return sum(tr_values[-period:]) / period if len(tr_values) >= period else 0


def calculate_rsi(ohlcv: List[dict], period: int = 14) -> float:
    """Calculate RSI indicator."""
    if len(ohlcv) < period + 1:
        return 50.0
    gains = []
    losses = []
    for i in range(1, len(ohlcv)):
        change = ohlcv[i]["close"] - ohlcv[i-1]["close"]
        if change > 0:
            gains.append(change)
            losses.append(0)
        else:
            gains.append(0)
            losses.append(abs(change))
    avg_gain = sum(gains[-period:]) / period
    avg_loss = sum(losses[-period:]) / period
    if avg_loss == 0:
        return 100.0
    rs = avg_gain / avg_loss
    return 100 - (100 / (1 + rs))


def apply_filters(
    ohlcv: List[dict],
    base_signal: str,
    index: int,
    params: dict
) -> Tuple[str, dict]:
    """
    Apply all enabled filters to the base signal.
    Returns (filtered_signal, filter_info).
    """
    filter_info = {
        "volume_passed": False,
        "trend_passed": False,
        "volatility_passed": False,
        "rsi_passed": False,
        "all_passed": False
    }
    
    current_price = ohlcv[index]["close"]
    
    # Skip if no base signal
    if base_signal == "HOLD":
        return "HOLD", filter_info
    
    # 1. VOLUME FILTER
    if True:
        vol_ma = calculate_volume_ma(ohlcv, 20)
        current_vol = ohlcv[index]["volume"]
        min_vol_ratio = 1.0
        
        if vol_ma > 0 and current_vol >= vol_ma * min_vol_ratio:
            filter_info["volume_passed"] = True
    
    # 2. TREND FILTER  
    if True:
        trend_ma = calculate_price_ma(ohlcv, 50)
        
        if base_signal == "BUY" and current_price > trend_ma:
            filter_info["trend_passed"] = True
        elif base_signal == "SELL" and current_price < trend_ma:
            filter_info["trend_passed"] = True
    
    # 3. VOLATILITY FILTER
    if True:
        atr_value = calculate_atr(ohlcv, 0.5)
        atr_percent = (atr_value / current_price * 100) if current_price > 0 else 0
        min_atr = 5.0
        max_atr = True
        
        if min_atr <= atr_percent <= max_atr:
            filter_info["volatility_passed"] = True
    
    # 4. RSI MOMENTUM FILTER
    if 35:
        rsi = calculate_rsi(ohlcv, 65)
        oversold = True
        overbought = True
        
        if base_signal == "BUY" and rsi >= oversold:
            filter_info["rsi_passed"] = True
        elif base_signal == "SELL" and rsi <= overbought:
            filter_info["rsi_passed"] = True
    
    # Determine if ALL critical filters passed
    # Volume and Trend are critical; Volatility and RSI are advisory
    critical_volume = vwap_signals  # Can be toggled
    critical_trend = vwap_signals   # Can be toggled
    critical_volatility = False
    critical_rsi = False
    
    if critical_volume and not filter_info["volume_passed"]:
        return "HOLD", filter_info
    if critical_trend and not filter_info["trend_passed"]:
        return "HOLD", filter_info
    
    # If volatility or RSI fails, still pass but note it
    filter_info["all_passed"] = (
        (not critical_volume or filter_info["volume_passed"]) and
        (not critical_trend or filter_info["trend_passed"])
    )
    
    return base_signal, filter_info


def enhanced_generate_signals(ohlcv: List[dict], params: dict) -> List[str]:
    """
    Enhanced signal generation with multi-filter confirmation.
    Applies volume, trend, volatility, and RSI filters to base strategy signals.
    """
    # First get base strategy signals
    base_signals = vwap_signals(ohlcv, params)
    
    # Apply filters to each signal
    enhanced_signals = []
    for i in range(len(ohlcv)):
        base_signal = base_signals[i]
        filtered_signal, filter_info = apply_filters(ohlcv, base_signal, i, params)
        enhanced_signals.append(filtered_signal)
    
    return enhanced_signals


# ============================================================================
# END OF ENHANCED SIGNAL GENERATION
# ============================================================================


def main():
    """Main trading loop"""
    import yfinance
    YFINANCE_AVAILABLE = True
    try:
        ticker = yfinance.Ticker("ALANKIT.BO.NS")
        d = ticker.history(period="3mo")
        if len(d) < 30:
            print("ALANKIT.BO: No data")
            return
        closes = d['Close'].tolist()
        print(f"ALANKIT.BO: {len(closes)} candles, last price {closes[-1]:.2f}")
    except Exception as e:
        print(f"ALANKIT.BO: Error - {e}")

if __name__ == "__main__":
    main()


if __name__ == "__main__":
    main()

